Data Cleaning : Agents

In [8]:
import pandas as pd
df_agents = pd.read_csv(r'E:\5_Portofolio Data Analyst\1_Real_Estate_Analysis\Real_Estate_Data.csv\agents.csv')
df_agents.head()

  agent_id  agent_city  experience_years  base_commission_rate  agent_rating
0   A00001    Barishal               4.6                0.0259          3.07
1   A00002  Chattogram               5.2                0.0314          3.43
2   A00003     Rangpur               4.7                0.0201          3.83
3   A00004      Sylhet               6.0                0.0260          3.95
4   A00005       Dhaka              10.2                0.0323          4.02

In [9]:
df_agents.shape

(300, 5)

In [15]:
df_agents.info()

<class 'pandas.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 5 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   agent_id              300 non-null    str
 1   agent_city            300 non-null    str
 2   experience_years      300 non-null    float64
 3   base_commission_rate  300 non-null    float64
 4   agent_rating          296 non-null    float64
dtypes: float64(3), str(2)
memory usage: 11.8 KB

In [16]:
df_agents.describe()

       experience_years  base_commission_rate  agent_rating
count        300.000000            300.000000    296.000000
mean           5.525333              0.024756      4.198074
std            3.073986              0.004032      0.427205
min            0.000000              0.015000      2.560000
25%            3.300000              0.021975      3.947500
50%            5.700000              0.024950      4.220000
75%            7.600000              0.027350      4.480000
max           13.800000              0.035000      5.000000

In [11]:
df_agents.duplicated().sum()

np.int64(0)

In [13]:
df_agents.isnull().sum()

agent_id                0
agent_city              0
experience_years        0
base_commission_rate    0
agent_rating            4
dtype: int64

In [20]:
##Handling missing values
df_agents['agent_rating'].median()
#Filled missing agent_rating values using the median to reduce the impact of outliers and maintain data distribution.
df_agents['agent_rating'] = df['agent_rating'].fillna(
    df['agent_rating'].median())
df_agents.isnull().sum()

agent_id                0
agent_city              0
experience_years        0
base_commission_rate    0
agent_rating            0
dtype: int64

In [25]:
df_agents['agent_city'].unique()
df_agents['agent_city'] = df_agents['agent_city'].str.strip().str.title()

In [32]:
df_agents[df['experience_years']==0.]

    agent_id  agent_city  experience_years  base_commission_rate  agent_rating
5     A00006  Mymensingh               0.0                0.0184          4.22
10    A00011  Chattogram               0.0                0.0260          4.42
52    A00053    Barishal               0.0                0.0190          4.30
57    A00058      Khulna               0.0                0.0244          4.04
89    A00090      Khulna               0.0                0.0267          4.22
102   A00103       Dhaka               0.0                0.0263          4.59
120   A00121    Rajshahi               0.0                0.0241          4.54
123   A00124  Chattogram               0.0                0.0278          4.85
145   A00146       Dhaka               0.0                0.0242          4.42
175   A00176       Dhaka               0.0                0.0275          4.71
208   A00209       Dhaka               0.0                0.0290          4.91
210   A00211      Sylhet               0.0                0.0291          4.64
216   A00217       Dhaka               0.0                0.0301          3.71
250   A00251    Rajshahi               0.0                0.0323          4.16
292   A00293  Mymensingh               0.0                0.0259          3.61

In [155]:
df_agents.info()

<class 'pandas.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 5 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   agent_id              300 non-null    str
 1   agent_city            300 non-null    str
 2   experience_years      300 non-null    float64
 3   base_commission_rate  300 non-null    float64
 4   agent_rating          300 non-null    float64
dtypes: float64(3), str(2)
memory usage: 11.8 KB

In [156]:
df_agents.to_csv(r'E:\5_Portofolio Data Analyst\1_Real_Estate_Analysis\Data Preparation\Clean_Dataset\Agents.csv', index=False)

Data Cleaning : Customers

In [39]:
import pandas as pd

df_customers = pd.read_csv(r'E:\5_Portofolio Data Analyst\1_Real_Estate_Analysis\Real_Estate_Data.csv\customers.csv')
df_customers.head()

,customer_id,signup_date,home_city,segment,age,household_size,income_band,acquisition_channel,propensity_score
0,C000001,2022-06-30,Dhaka,End-User,39.0,6,Mid,Organic,0.588
1,C000002,2024-01-25,Mymensingh,Investor,28.0,4,NaN,Paid Search,0.524
2,C000003,2024-06-10,Chattogram,Renter-to-Owner,24.0,4,Low,Paid Search,0.451
3,C000004,2022-07-06,Dhaka,Investor,42.0,6,Upper-Mid,Marketplace,0.853
4,C000005,2024-03-11,Mymensingh,End-User,33.0,3,Lower-Mid,Facebook,0.503

In [40]:
df_customers.shape

(8000, 9)

In [41]:
df_customers.info()

<class 'pandas.DataFrame'>
RangeIndex: 8000 entries, 0 to 7999
Data columns (total 9 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   customer_id          8000 non-null   str
 1   signup_date          8000 non-null   str
 2   home_city            8000 non-null   str
 3   segment              8000 non-null   str
 4   age                  7837 non-null   float64
 5   household_size       8000 non-null   int64
 6   income_band          7531 non-null   str
 7   acquisition_channel  8000 non-null   str
 8   propensity_score     8000 non-null   float64
dtypes: float64(2), int64(1), str(6)
memory usage: 562.6 KB

In [52]:
#handling invalid data format
df_customers['signup_date'] = pd.to_datetime(df_customers['signup_date'])

In [48]:
df_customers.describe()

               age  household_size  propensity_score
count  7837.000000     8000.000000       8000.000000
mean     34.300880        3.712250          0.589423
std       8.749262        1.317637          0.148510
min      18.000000        1.000000          0.109000
25%      28.000000        3.000000          0.486000
50%      34.000000        4.000000          0.586000
75%      40.000000        5.000000          0.688000
max      67.000000        8.000000          0.950000

In [45]:
df_customers.duplicated().sum()

np.int64(0)

In [53]:
df_customers.isnull().sum()

customer_id              0
signup_date              0
home_city                0
segment                  0
age                    163
household_size           0
income_band            469
acquisition_channel      0
propensity_score         0
dtype: int64

In [55]:
##Handling missing value for age column using median
df_customers['age'] = df_customers['age'].fillna(df_customers['age'].median())

In [57]:
df_customers['income_band'].unique()

<StringArray>
['Mid', nan, 'Low', 'Upper-Mid', 'Lower-Mid', 'High']
Length: 6, dtype: str

In [58]:
##Handling missing value for income_band 
df_customers['income_band'] = df_customers['income_band'].fillna('Unknown')

In [70]:
print(df_customers['home_city'].unique())
print(df_customers['segment'].unique())
print(df_customers['income_band'].unique())
print(df_customers['acquisition_channel'].unique())

<StringArray>
[     'Dhaka', 'Mymensingh', 'Chattogram',   'Barishal',    'Rangpur',
     'Khulna',   'Rajshahi',     'Sylhet']
Length: 8, dtype: str
<StringArray>
['End-User', 'Investor', 'Renter-to-Owner', 'Business Buyer']
Length: 4, dtype: str
<StringArray>
['Mid', 'Unknown', 'Low', 'Upper-Mid', 'Lower-Mid', 'High']
Length: 6, dtype: str
<StringArray>
[       'Organic',    'Paid Search',    'Marketplace',       'Facebook',
          'Email',       'Referral', 'Broker Network']
Length: 7, dtype: str

In [71]:
df_customers.info()

<class 'pandas.DataFrame'>
RangeIndex: 8000 entries, 0 to 7999
Data columns (total 9 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   customer_id          8000 non-null   str
 1   signup_date          8000 non-null   datetime64[us]
 2   home_city            8000 non-null   str
 3   segment              8000 non-null   str
 4   age                  8000 non-null   float64
 5   household_size       8000 non-null   int64
 6   income_band          8000 non-null   str
 7   acquisition_channel  8000 non-null   str
 8   propensity_score     8000 non-null   float64
dtypes: datetime64[us](1), float64(2), int64(1), str(5)
memory usage: 562.6 KB

In [157]:
df_customers.to_csv(r'E:\5_Portofolio Data Analyst\1_Real_Estate_Analysis\Data Preparation\Clean_Dataset\customer.csv', index=False)

Data Cleaning : listings

In [74]:
import pandas as pd

df_listings = pd.read_csv(r'E:\5_Portofolio Data Analyst\1_Real_Estate_Analysis\Real_Estate_Data.csv\listings.csv')

In [75]:
df_listings.head()

,listing_id,property_id,agent_id,listing_date,listing_channel,listed_price,sold_flag,days_on_market,close_date
0,L0000001,P001435,A00259,2022-03-18,Open,13760987,True,19,2022-04-06
1,L0000002,P000116,A00138,2022-11-13,Open,13163048,True,49,2023-01-01
2,L0000003,P004113,A00039,2024-08-06,Exclusive,6046818,True,56,2024-10-01
3,L0000004,P003060,A00024,2024-05-10,Exclusive,14552395,False,128,NaN
4,L0000005,P002252,A00101,2022-05-02,Exclusive,19773287,False,40,NaN

In [76]:
df_listings.info()

<class 'pandas.DataFrame'>
RangeIndex: 8500 entries, 0 to 8499
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   listing_id       8500 non-null   str
 1   property_id      8500 non-null   str
 2   agent_id         8500 non-null   str
 3   listing_date     8500 non-null   str
 4   listing_channel  8500 non-null   str
 5   listed_price     8500 non-null   int64
 6   sold_flag        8500 non-null   bool
 7   days_on_market   8500 non-null   int64
 8   close_date       3822 non-null   str
dtypes: bool(1), int64(2), str(6)
memory usage: 539.7 KB

In [95]:
print(df_listings['listing_channel'].unique())

<StringArray>
['Open', 'Exclusive', 'Partner']
Length: 3, dtype: str

In [86]:
df_listings.describe()

,listing_date,listed_price,days_on_market,close_date
count,8500,8.500000e+03,8500.000000,3822
mean,2023-06-28 15:57:10.588235,1.418532e+07,73.813294,2023-08-21 18:09:13.846153
min,2022-01-01 00:00:00,2.662595e+06,3.000000,2022-01-04 00:00:00
25%,2022-09-23 00:00:00,8.628890e+06,38.000000,2022-11-19 00:00:00
50%,2023-06-30 00:00:00,1.194630e+07,62.000000,2023-09-03 00:00:00
75%,2024-03-31 00:00:00,1.732615e+07,102.000000,2024-05-26 00:00:00
max,2024-12-24 00:00:00,7.267558e+07,314.000000,2025-04-10 00:00:00
std,NaN,8.047140e+06,50.052481,NaN

In [77]:
df_listings['listing_date'] = pd.to_datetime(df_listings['listing_date'])

In [91]:
df_listings.isnull().sum()

listing_id            0
property_id           0
agent_id              0
listing_date          0
listing_channel       0
listed_price          0
sold_flag             0
days_on_market        0
close_date         4678
listing_status        0
dtype: int64

In [80]:
## Handling missing value in the close_date column
## Missing close_date values were kept as they represent active listings that have not been closed yet
df_listings['close_date'] = pd.to_datetime(
    df_listings['close_date'],
    errors='coerce'
)

In [82]:
##A new listing_status column was created to identify active and closed listings based on the availability of close_date
import numpy as np
df_listings['listing_status'] = np.where(
    df_listings['close_date'].isna(),
    'Active',
    'Closed'
)

In [90]:
df_listings.duplicated().sum()

np.int64(0)

In [84]:
df_listings.info()

<class 'pandas.DataFrame'>
RangeIndex: 8500 entries, 0 to 8499
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   listing_id       8500 non-null   str
 1   property_id      8500 non-null   str
 2   agent_id         8500 non-null   str
 3   listing_date     8500 non-null   datetime64[us]
 4   listing_channel  8500 non-null   str
 5   listed_price     8500 non-null   int64
 6   sold_flag        8500 non-null   bool
 7   days_on_market   8500 non-null   int64
 8   close_date       3822 non-null   datetime64[us]
 9   listing_status   8500 non-null   str
dtypes: bool(1), datetime64[us](2), int64(2), str(5)
memory usage: 606.1 KB

In [158]:
df_listings.to_csv(r'E:\5_Portofolio Data Analyst\1_Real_Estate_Analysis\Data Preparation\Clean_Dataset\listings.csv', index=False)

Data Cleaning : Poperties

In [88]:
import pandas as pd

df_properties = pd.read_csv(r'E:\5_Portofolio Data Analyst\1_Real_Estate_Analysis\Real_Estate_Data.csv\properties.csv')

In [89]:
df_properties.info()

<class 'pandas.DataFrame'>
RangeIndex: 4500 entries, 0 to 4499
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   property_id        4500 non-null   str
 1   city               4500 non-null   str
 2   neighborhood_code  4500 non-null   str
 3   property_type      4500 non-null   str
 4   size_sqm           4500 non-null   float64
 5   bedrooms           4500 non-null   int64
 6   bathrooms          4500 non-null   int64
 7   year_built         4500 non-null   int64
 8   location_score     4297 non-null   float64
 9   amenities_count    4290 non-null   float64
 10  list_price         4500 non-null   int64
 11  has_parking        4500 non-null   bool
 12  near_transit       4500 non-null   bool
 13  near_school        4500 non-null   bool
dtypes: bool(3), float64(3), int64(4), str(4)
memory usage: 400.0 KB

In [92]:
df_properties.duplicated().sum()

np.int64(0)

In [97]:
print(df_properties['city'].unique())
print(df_properties['property_type'].unique())

<StringArray>
[  'Barishal',   'Rajshahi',    'Rangpur', 'Chattogram',      'Dhaka',
     'Khulna', 'Mymensingh',     'Sylhet']
Length: 8, dtype: str
<StringArray>
['Land', 'Apartment', 'House', 'Commercial']
Length: 4, dtype: str

In [99]:
df_properties.isnull().sum()

property_id            0
city                   0
neighborhood_code      0
property_type          0
size_sqm               0
bedrooms               0
bathrooms              0
year_built             0
location_score       203
amenities_count      210
list_price             0
has_parking            0
near_transit           0
near_school            0
dtype: int64

In [100]:
#Handling missing value for location_score
df_properties['location_score'] = df_properties['location_score'].fillna(df_properties['location_score'].median())

In [101]:
#Handling missing value for amenities_count
df_properties['amenities_count'] = df_properties['amenities_count'].fillna(df_properties['amenities_count'].median())

In [102]:
df_properties.describe()

,size_sqm,bedrooms,bathrooms,year_built,location_score,amenities_count,list_price
count,4500.000000,4500.000000,4500.000000,4500.000000,4500.000000,4500.000000,4.500000e+03
mean,133.786956,2.086444,1.659111,2013.712000,0.654908,7.536444,1.405811e+07
std,70.716231,1.394538,1.111587,7.407678,0.154241,2.545563,7.832863e+06
min,35.000000,0.000000,0.000000,1985.000000,0.150000,1.000000,3.208540e+06
25%,86.100000,1.000000,1.000000,2009.000000,0.554000,6.000000,8.618064e+06
50%,114.700000,2.000000,2.000000,2014.000000,0.658000,8.000000,1.187603e+07
75%,163.775000,3.000000,2.000000,2019.000000,0.758000,9.000000,1.716078e+07
max,660.100000,6.000000,6.000000,2025.000000,0.950000,15.000000,7.030357e+07

In [105]:
df_properties.info()

<class 'pandas.DataFrame'>
RangeIndex: 4500 entries, 0 to 4499
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   property_id        4500 non-null   str
 1   city               4500 non-null   str
 2   neighborhood_code  4500 non-null   str
 3   property_type      4500 non-null   str
 4   size_sqm           4500 non-null   float64
 5   bedrooms           4500 non-null   int64
 6   bathrooms          4500 non-null   int64
 7   year_built         4500 non-null   int64
 8   location_score     4500 non-null   float64
 9   amenities_count    4500 non-null   float64
 10  list_price         4500 non-null   int64
 11  has_parking        4500 non-null   bool
 12  near_transit       4500 non-null   bool
 13  near_school        4500 non-null   bool
dtypes: bool(3), float64(3), int64(4), str(4)
memory usage: 400.0 KB

In [159]:
df_properties.to_csv(r'E:\5_Portofolio Data Analyst\1_Real_Estate_Analysis\Data Preparation\Clean_Dataset\properties.csv',index=False)

Data Cleaning : Transactions

In [108]:
import pandas as pd

df_transactions = pd.read_csv(r'E:\5_Portofolio Data Analyst\1_Real_Estate_Analysis\Real_Estate_Data.csv\transactions.csv')
df_transactions.head()

,transaction_id,listing_id,property_id,agent_id,customer_id,city,deal_date,deal_price,commission_amount,payment_mode,deal_status
0,T00000001,L0004979,P004474,A00179,C000275,Dhaka,2024-10-20,20951990.0,530085,Cash,Completed
1,T00000002,L0001009,P002023,A00059,C004923,Dhaka,2023-09-07,10704517.0,294374,Mortgage,Completed
2,T00000003,L0008313,P004075,A00285,C005386,Chattogram,2024-05-30,11306054.0,315439,Mortgage,Completed
3,T00000004,L0006698,P004469,A00070,C005323,Chattogram,2023-03-10,7998580.0,205564,Mortgage,Completed
4,T00000005,L0002447,P000751,A00291,C001569,Rangpur,2023-07-23,5351976.0,131659,Mortgage,Completed

In [110]:
df_transactions.info()

<class 'pandas.DataFrame'>
RangeIndex: 3975 entries, 0 to 3974
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   transaction_id     3975 non-null   str
 1   listing_id         3975 non-null   str
 2   property_id        3975 non-null   str
 3   agent_id           3975 non-null   str
 4   customer_id        3975 non-null   str
 5   city               3975 non-null   str
 6   deal_date          3975 non-null   str
 7   deal_price         3922 non-null   float64
 8   commission_amount  3975 non-null   int64
 9   payment_mode       3926 non-null   str
 10  deal_status        3975 non-null   str
dtypes: float64(1), int64(1), str(9)
memory usage: 341.7 KB

In [111]:
df_transactions.describe()

         deal_price  commission_amount
count  3.922000e+03       3.975000e+03
mean   1.376959e+07       3.415096e+05
std    7.823635e+06       2.082439e+05
min    2.992547e+06       5.973000e+04
25%    8.345106e+06       2.023005e+05
50%    1.175462e+07       2.834110e+05
75%    1.665520e+07       4.154985e+05
max    6.651116e+07       2.065750e+06

In [112]:
df_transactions.isnull().sum()

transaction_id        0
listing_id            0
property_id           0
agent_id              0
customer_id           0
city                  0
deal_date             0
deal_price           53
commission_amount     0
payment_mode         49
deal_status           0
dtype: int64

In [114]:
(df_transactions['deal_price'].isnull().sum() / len(df_transactions)) * 100

np.float64(1.3333333333333335)

In [115]:
#Handling Missing Value for deal_price
#Missing values in the deal_price column (1.33%) were removed because valid deal prices are required for accurate transaction analysis
df_transactions = df_transactions.dropna(
    subset=['deal_price']
)

In [116]:
df_transactions['deal_price'].isnull().sum()

np.int64(0)

In [117]:
df_transactions.isnull().sum()

transaction_id        0
listing_id            0
property_id           0
agent_id              0
customer_id           0
city                  0
deal_date             0
deal_price            0
commission_amount     0
payment_mode         49
deal_status           0
dtype: int64

In [118]:
#Handling missing value for payment_mode by filling missing value with 'Unknown'
df_transactions['payment_mode'] = df_transactions['payment_mode'].fillna('Unknown')

In [121]:
print(df_transactions['city'].unique())
print(df_transactions['payment_mode'].unique())
print(df_transactions['deal_status'].unique())

<StringArray>
[     'Dhaka', 'Chattogram',    'Rangpur', 'Mymensingh',   'Rajshahi',
     'Sylhet',     'Khulna',   'Barishal']
Length: 8, dtype: str
<StringArray>
['Cash', 'Mortgage', 'Installment', 'Unknown']
Length: 4, dtype: str
<StringArray>
['Completed', 'Disputed']
Length: 2, dtype: str

In [122]:
df_transactions.info()

<class 'pandas.DataFrame'>
Index: 3922 entries, 0 to 3974
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   transaction_id     3922 non-null   str
 1   listing_id         3922 non-null   str
 2   property_id        3922 non-null   str
 3   agent_id           3922 non-null   str
 4   customer_id        3922 non-null   str
 5   city               3922 non-null   str
 6   deal_date          3922 non-null   str
 7   deal_price         3922 non-null   float64
 8   commission_amount  3922 non-null   int64
 9   payment_mode       3922 non-null   str
 10  deal_status        3922 non-null   str
dtypes: float64(1), int64(1), str(9)
memory usage: 367.7 KB

In [160]:
df_transactions.to_csv(r'E:\5_Portofolio Data Analyst\1_Real_Estate_Analysis\Data Preparation\Clean_Dataset\transactions.csv',index=False)

Data Cleaning : Interactions

In [126]:
import pandas as pd
df_interactions = pd.read_csv(r'E:\5_Portofolio Data Analyst\1_Real_Estate_Analysis\Real_Estate_Data.csv\interactions.csv')
df_interactions.head()

,interaction_id,event_ts,customer_id,property_id,interaction_type,device,source,session_minutes,intent_sentiment
0,I000000001,2024-12-29,C006978,P001347,Call,Desktop,App,6.8,NaN
1,I000000002,2024-06-03,C002346,P002951,Call,Mobile,App,6.1,0.352
2,I000000003,2023-06-27,C005380,P003276,Visit,Desktop,App,5.4,0.895
3,I000000004,2024-12-16,C001723,P004482,View,Mobile,Web,4.4,NaN
4,I000000005,2022-09-27,C001583,P001564,Call,Mobile,App,10.0,0.544

In [127]:
df_interactions.info()

<class 'pandas.DataFrame'>
RangeIndex: 140000 entries, 0 to 139999
Data columns (total 9 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   interaction_id    140000 non-null  str
 1   event_ts          140000 non-null  str
 2   customer_id       140000 non-null  str
 3   property_id       140000 non-null  str
 4   interaction_type  140000 non-null  str
 5   device            138645 non-null  str
 6   source            140000 non-null  str
 7   session_minutes   140000 non-null  float64
 8   intent_sentiment  43979 non-null   float64
dtypes: float64(2), str(7)
memory usage: 9.6 MB

In [129]:
df_interactions['event_ts'] = pd.to_datetime(df_interactions['event_ts'])

In [131]:
df_interactions.isnull().sum()

interaction_id          0
event_ts                0
customer_id             0
property_id             0
interaction_type        0
device               1355
source                  0
session_minutes         0
intent_sentiment    96021
dtype: int64

In [ ]:
#Handling missing value for device column by filling with 'unknown'
#Handling missing value for intent_sentment by using median value

df_interactions['device'] = df_interactions['device'].fillna('Unknown')

In [133]:
df_interactions.describe()

                         event_ts  session_minutes  intent_sentiment
count                      140000    140000.000000      43979.000000
mean   2024-01-13 13:50:47.245714         8.387776          0.347276
min           2022-01-01 00:00:00         1.000000         -1.000000
25%           2023-07-15 00:00:00         5.300000          0.118000
50%           2024-02-24 00:00:00         7.400000          0.351000
75%           2024-08-16 00:00:00        10.400000          0.589000
max           2025-03-30 00:00:00        74.000000          1.000000
std                           NaN         4.468761          0.339068

In [135]:
df_interactions.info()

<class 'pandas.DataFrame'>
RangeIndex: 140000 entries, 0 to 139999
Data columns (total 9 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   interaction_id    140000 non-null  str
 1   event_ts          140000 non-null  datetime64[us]
 2   customer_id       140000 non-null  str
 3   property_id       140000 non-null  str
 4   interaction_type  140000 non-null  str
 5   device            140000 non-null  str
 6   source            140000 non-null  str
 7   session_minutes   140000 non-null  float64
 8   intent_sentiment  43979 non-null   float64
dtypes: datetime64[us](1), float64(2), str(6)
memory usage: 9.6 MB

In [137]:
print(df_interactions['device'].unique())
print(df_interactions['interaction_type'].unique())
print(df_interactions['source'].unique())

<StringArray>
['Desktop', 'Mobile', 'Unknown']
Length: 3, dtype: str
<StringArray>
['Call', 'Visit', 'View', 'Save', 'Inquiry', 'Offer']
Length: 6, dtype: str
<StringArray>
['App', 'Web']
Length: 2, dtype: str

In [ ]:
#Missing values in intent_sentiment left unchanged because the missing proportion was very high, and imputing them could distort the actual sentiment distributio

In [161]:
df_interactions.to_csv(r'E:\5_Portofolio Data Analyst\1_Real_Estate_Analysis\Data Preparation\Clean_Dataset\interactions.csv',index=False)

Data Cleaning : Customers Monthly Metrics

In [141]:
import pandas as pd
df_cmm = pd.read_csv(r'E:\5_Portofolio Data Analyst\1_Real_Estate_Analysis\Real_Estate_Data.csv\customer_monthly_metrics.csv')
df_cmm.head()

,customer_id,month,signup_month,propensity_score,segment,acquisition_channel,home_city,calls,inquirys,offers,...,visits,sessions,avg_session_min,revenue,deals,engagement_score,engagement_3m,churn_risk,churned,churn_month
0,C000001,2022-06-01,2022-06-01,0.588,End-User,Organic,Dhaka,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0000,0.0000,0.2745,False,2024-01-01
1,C000001,2022-07-01,2022-06-01,0.588,End-User,Organic,Dhaka,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0000,0.0000,0.3052,False,2024-01-01
2,C000001,2022-08-01,2022-06-01,0.588,End-User,Organic,Dhaka,0.0,0.0,0.0,...,0.0,1.0,6.4,0.0,0.0,0.0564,0.0188,0.1869,False,2024-01-01
3,C000001,2022-09-01,2022-06-01,0.588,End-User,Organic,Dhaka,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0000,0.0188,0.2100,False,2024-01-01
4,C000001,2022-10-01,2022-06-01,0.588,End-User,Organic,Dhaka,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0000,0.0188,0.2572,False,2024-01-01

In [142]:
df_cmm.info()

<class 'pandas.DataFrame'>
RangeIndex: 119906 entries, 0 to 119905
Data columns (total 22 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   customer_id          119906 non-null  str
 1   month                119906 non-null  str
 2   signup_month         119906 non-null  str
 3   propensity_score     119906 non-null  float64
 4   segment              119906 non-null  str
 5   acquisition_channel  119906 non-null  str
 6   home_city            119906 non-null  str
 7   calls                119906 non-null  float64
 8   inquirys             119906 non-null  float64
 9   offers               119906 non-null  float64
 10  saves                119906 non-null  float64
 11  views                119906 non-null  float64
 12  visits               119906 non-null  float64
 13  sessions             119906 non-null  float64
 14  avg_session_min      119906 non-null  float64
 15  revenue              119906 non-null  float64
 16  deals                119906 non-null  float64
 17  engagement_score     119906 non-null  float64
 18  engagement_3m        119906 non-null  float64
 19  churn_risk           119906 non-null  float64
 20  churned              116295 non-null  object
 21  churn_month          46655 non-null   str
dtypes: float64(14), object(1), str(7)
memory usage: 20.1+ MB

In [143]:
df_cmm['month'] = pd.to_datetime(df_cmm['month'])
df_cmm['signup_month'] = pd.to_datetime(df_cmm['signup_month'])
df_cmm['churn_month'] = pd.to_datetime(df_cmm['churn_month'])

In [144]:
df_cmm.duplicated().sum()

np.int64(0)

In [145]:
df_cmm.isnull().sum()

customer_id                0
month                      0
signup_month               0
propensity_score           0
segment                    0
acquisition_channel        0
home_city                  0
calls                      0
inquirys                   0
offers                     0
saves                      0
views                      0
visits                     0
sessions                   0
avg_session_min            0
revenue                    0
deals                      0
engagement_score           0
engagement_3m              0
churn_risk                 0
churned                 3611
churn_month            73251
dtype: int64

In [148]:
df_cmm['churned'] = df_cmm['churned'].fillna('UNKNOWN')

In [152]:
#Added a churn_status column to identify customers with missing churn_month values as active customers
df_cmm['churn_status'] = df_cmm['churn_month'].apply(
    lambda x: 'Churned' if pd.notna(x) else 'Active'
)

In [166]:
df_cmm.to_csv(r'E:\5_Portofolio Data Analyst\1_Real_Estate_Analysis\Data Preparation\Clean_Dataset\customer_monthly_metrics.csv',index=False)